---
- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: update all packages
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install utils
    apt:
      name: htop 
      name: net-tools
